version: '3'
networks: 
    myapp:
        driver: bridge
services: 
    database:
        image: mysql:5.7
        container_name: app_mysql
        command:  --innodb-use-native-aio=0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306"
        volumes:
            - "./data/mysql:/var/lib/mysql"
        networks: 
            - myapp
    redis:
        container_name: app_redis
        image: redis
        ports:
            - "6379"
        volumes:
            - "./data/redis:/data"
        restart: always
        networks: 
            - myapp
    php-app:
        build: ./src
        container_name: app_php
        entrypoint: sh entrypoint.sh php-fpm
        environment: 
            - DB_HOST=database
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_PASSWORD=root
        volumes:
            - "./src/files:/var/www"
        ports: 
            - "8000:8000"
        networks: 
            - myapp