apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
spec:
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: nginx
              image: nginx:1.16-alpine
              command: ["/bin/sh","-c","touch /usr/share/nginx/html/index.php; nginx -g 'daemon off;'"]
              ports:
              - containerPort: 80

              volumeMounts:
              - mountPath: /etc/nginx/conf.d
                name: nginx-conf
                readOnly: true
            
            volumes:
            - name: nginx-conf
              configMap:
                name: nginx-config
                items: 
                - key: nginx.conf
                  path: nginx.conf

---

apiVersion: v1
kind: Service
metadata:
    name: nginx-service
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: nginx