FROM php:7.4-fpm-alpine
RUN apk add bash && docker-php-ext-install pdo_mysql

WORKDIR /var/www

RUN rm -rf html
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && chmod +x /usr/bin/composer 

COPY ./src/files /var/www

RUN composer install && \
    php artisan config:cache && \
    chmod -R 777 storage
RUN ln -s public html
 
EXPOSE 9000