FROM php:7.4-fpm-alpine
WORKDIR /var/www

RUN rm -rf html
RUN ln -s public html
RUN apk add bash && docker-php-ext-install pdo_mysql
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer && chmod +x /usr/bin/composer 

RUN ./files /var/www
RUN composer install && \
    php artisan config:cache && \
    chmod -R 777 storage
 
EXPOSE 9000